### ISSUE TITLE
List of cities ordered by crimes per capita

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-front-end#103]
## Issue Description
Create a screen that list all the cities ordered by crimes per capita.
The order should be of the higher to the lowest (DESC).
Create a button to go to navigate to this screen, this button should be placed in the statistics screen of a city, like this [image](https://user-images.githubusercontent.com/29635581/100562386-55c10e80-329a-11eb-8b37-7e9e7ecaa825.png).

## How it will be validated
To validate the issue the following tests will be done:

- The reviewer will navigate to the statistics of a city and click the button to order cities. The app should load a list of cities ordered by the city with most crime at the top.
- In the list of cities ordered by crimes per capita the reviewer will filter the list by the crime "Furto", the list should update the values of each city to this type of crime.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Create a button at the city statistics screen to navigate to the ordered list of cities.
- [x] Create the list of cities with a bar that indicates the crimes of that city.
- [x] Order the list with the cities with most crimes per capita at the top.
- [x] Create a select that filter the crimes by type.
