### ISSUE TITLE
Viewing, editing and deleting a user profile

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#11]
## Issue Description
Make a screen for viewing and editing user profile with the [prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/produto/prototype/) style. In case of suggestions for changes, inform the team that we will discuss this together.

In the preview the password cannot be shown. Username can't be edited, show it in a non-editable box. 

When editing password use its appropriate type to not show the entered characters, make the user confirm the new password.

Make sure to validate data in editing case and show user friendly messages in case of problems in any field. Follow the validations available in the [user crud issue](https://github.com/fga-eps-mds/2020.1-stay-safe-docs/issues/29), display database message in a user-friendly manner if user tries to register an email that already exists. 

Create another screen for user to delete his account also following [prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/produto/prototype/) style. After he click on delete account button show him a modal asking if he is sure of that. Discard his token and redirect him to the home page after this procedure. 

## Additional context
The three defined functionalities must communicate with the backend, the types of requests to be made (get, patch and delete) can be found in the [user view file](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/blob/develop/src/views/user.py).

The backend will return a token in patch request, make sure to save the new token and attribute to the user.

## Tasks:
- [x] Implement user profile visualization
- [x] Implement user profile editing 
- [x] Implement user profile deleting
