### ISSUE TITLE
Map Fixes

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#112]
## Issue Description
Set of corrections for maps.

Right now the occurrence map filters change according to the state defined in the heat map. This should not happen, occurrence map filters must be static and use the crimes available at topic 6.3.2 in [architecture document](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/projeto/arquitetura/).

Move the screen on the heat map to the state where the map was generated.

Right now the load component not appears in the process of generate SP heat map. Ensure that the loading components appear properly.

## How it will be validated
To validate the issue the following tests will be done:

* The reviewer will change between the states on the heat map and try to find changes in the occurrence map filters. Expect to fail.
* The reviewer will verify that the correct displacement for the heat map is made after its generation.
* The reviewer will check if the loading component appears when generating the SP map.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Fix the occurrence filters
- [x] Move the screen to the heat map generated
- [ ] Restore load components
