### ISSUE TITLE
Pipeline configuration

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#14]
## Issue Description
Create a service on a docker-compose file to run the pipeline. The pipeline should build the project, run the eslint and run tests and generate a response to the user.

## Tasks:
- [x] Add the technologies used in the project.
- [x] Fix eslint errors, if needed.
- [x] Create docker-compose.
- [x] Update README.md
