### ISSUE TITLE
Create Login Screen

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#2]
## Issue Description
Create the login screen as defined in the high fidelity prototype using the flask API.

## Tasks:
- [x] Create login screen as defined in the high fidelity prototype.
- [x] Add request to authenticate the user with the flask API.
- [x] Save the user token returned by the API in the AsyncStorage.
