### ISSUE TITLE
Associate occurrence with a location on the map

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#21]
## Issue Description
Get all occurrences (sp and df) and plot a pin to each one in the map.
Create the functionality to let the user select a position in the map, with that position you should get the latitude and longitude of the position and send this with the creation or update of an occurence.
The design of this functionality should follow the high fidelity prototype.

## Tasks:
- [x] Place all occurrences in the map.
- [x] Let the user select a position in the map to create a occurrence.
- [x] Refactor the creation and update of an occurrence to send the position selected by the user.
