### ISSUE TITLE
View cities in heat map format according to the chosen filter

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#22]
## Issue Description
Create selection of filters in the frontend and show data in heat map shapes accordingly with the [prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/produto/prototype/) style. In case of suggestions for changes, inform the team that we will discuss this together.

Focus first on DF data. Setup secretary's environment on your local machine and run the DF spider to collect SSP data.

## Additional context
The defined functionality must communicate with the Secretary-Service, the types of requests to be made (get) can be found in the [crime view file](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/blob/develop/src/views/crime.py).

Take a specific crime at a time according to the filter chosen by the user. Consider the data from the last year (2019).

Request example: http://0.0.0.0:5000/api?secretary=df&crime=Latrocinio

Heat Map Colors (from red to orange to green): #ef0000, #ef3200, #ef4900, #ef5b00, #ef6a00, #ec7c00, #e88c00, #e39b00, #d6b000, #bfc600, #9ddb00, #65ef00

<a href="https://ibb.co/qWhdTW0"><img src="https://i.ibb.co/D8mt08G/Captura-de-Tela-20200928221042.png" alt="Captura-de-Tela-20200928221042" border="0"></a>

## Tasks:
- [x] Filter selection menu
- [x] Identify city areas
- [x] Paint a selected city area in the map
- [x] Connect with the MongoDB
- [x] Show all cities in heat map format
