### ISSUE TITLE
Viewing, editing and deleting events registered by the user

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#23]
## Issue Description
List all the occurrences that a user has, each row/card should show all informations (register_date, type, ...), show edit and delete button.
The update of the occurrence should use the create screen or a similar screen. (verify with the api if the update has some kind of limitation to old occurrences). If an occurrence is updated, the list should update to the new data.
The deletion of an occurrence should open a confirmation modal to the user, the deletion should only proceed if the user confirm. If the occurrence is successfully deleted, it should remove the row/card from the list.

## Tasks:
- [x] Create the list of occurrences.
- [x] Refactor or create a screen to update the information of an occurrence.
- [x] Create a function to delete an occurrence.
- [x] Update the list after update/delete.
