### ISSUE TITLE
Integrate with Google Maps API

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#3]
## Issue Description
Create and add the Google Maps in the home page screen.
Search and study about limitations and possibilities of how to to:
- Make pins in the map.
- Interact with pins to open a screen or modal to show informations about the pin.
- Interact with the map to see informations as selected neighborhood name and neighborhood rating (inserted by the stay-safe app).
- Price of using these features of the map.

## Tasks:
- [x] Add the map in the app.
- [x] Search about pins.
- [x] Search about how to interact with cities/neighborhood in the map.
- [x] Search about the price of the features mentioned above.
