### ISSUE TITLE
Update existing screens according to the prototype

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#32]
## Issue Description
Update existing screens and components according with the [prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/produto/prototype/) style.

If you find other components not mentioned below out of prototype style update them too.

## Tasks:
- [x] Profile Screen
- [x] Edit Profile Screen
- [x] Modal component when register occurrence
- [x] Modal component when editing profile
