### ISSUE TITLE
Filters for occurrence types in the maps and updating the occurrence types

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-front-end#42]
## Issue Description
Implements the screen of the selection of the filters of occurrence types and shows in the map only the occurrence of the type choose.
The screen of filters should be based in the respective [screen on the prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/images/prototype/Tela_dos_Filtros_Local.png). This screen should be integrated with the crimes filters screen, which already exists, from secretaries.
The allowed filters should be in accord with the service of the user and more then one filter is allowed in the same selection.

Furthermore, include the types "Furto a Transeunte" and "Furto de Veículo" as allowed types on register and updating of occurrences

## Tasks:
- [x] Update the register and the updating of occurrences with the new types allowed
- [x] Make the filters screen of types of occurrence integrated with the crimes filters screen from secretaries
- [x] Allow more than one type to be chosen from the same selection
- [x] Integrate with the service of the user doing the necessaries requests
- [x] Implement logic of show in maps only the occurrences received on the response from service of the user
