### ISSUE TITLE
Create a context and a theme

### ISSUE THREAD

**Issue by lboaventura25** [fga-eps-mds/2020.1-stay-safe-front-end#46]
## Issue Description
Create a context to easily provide a way to pass data through the component tree without having to pass props down manually at every level.

## Additional context
In addition to creating that context, you should also create a theme that provides palette colors for component tree.

## Tasks:
- [x] Create a context for username and token.
- [x] Create theme and dark theme.
- [x] Integrate the context with existing components.
