### ISSUE TITLE
View SP cities in heat map format

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#49]
## Issue Description
Create selection of filters in the frontend and show data in heat map shapes accordingly with the [prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/produto/prototype/) style. In case of suggestions for changes, inform the team that we will discuss this together.

Setup secretary's environment on your local machine and run the SP spider to collect SSP data.

## Additional context
The defined functionality must communicate with the Secretary-Service, the types of requests to be made (get) can be found in the [crime view file](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/blob/develop/src/views/crime.py) and [coordinates view file](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/blob/develop/src/views/crime.py) or acessing application swagger on your localhost adding /api/docs in the url.

Take a specific crime at a time according to the filter chosen by the user. Consider the data from the last year (September 2020 - September 2019).

Heat Map Colors (from red to orange to green): #ef2500, #ee5b00, #ea7b00, #e19a00, #bec500, #65ef00

<a href="https://ibb.co/qWhdTW0"><img src="https://i.ibb.co/D8mt08G/Captura-de-Tela-20200928221042.png" alt="Captura-de-Tela-20200928221042" border="0"></a>

## Tasks:
- [x] Filter selection menu
- [x] Identify city areas
- [x] Paint a selected city area in the map
- [x] Connect with the MongoDB
- [x] Show all cities in heat map format
