### ISSUE TITLE
View neighborhood review 

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#57]
## Issue Description
Create screen to view neighborhood review, the screen to be made has changes to what we have in [prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/produto/prototype/). Communicate with the team throughout the development of the functionality to validate design issues.

A button must be added to the statistics screen, with the text "Visualizar Bairros". By clicking on it the user will be redirected to a list of neighborhoods cards, each displaying neighborhood name, average stars, positive/neutral/negative characteristics and a button to evaluate neighborhood.

## Additional context
The defined functionality must communicate with the User-Service, the types of requests to be made (get) can be found in the [neighborhood view file](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/blob/develop/src/views/neighborhood.py) or acessing application swagger on your localhost adding /api/docs in the url.

Characteristics Colors (red/orange/green): #ef2500, #e19a00, #65ef00.  In case of suggestions for changes, inform the team that we will discuss this together.

## Tasks:
- [x] Add button in statistics screen and redirect user to list of neighborhoods of that city
- [x] Create card design and validate with the group
- [x] Collect real data for neighborhoods from user-service
