### ISSUE TITLE
Create a list of all neighborhood ratings of an user

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-front-end#59]
## Issue Description
Create a button inside the user profile to see all user ratings.
Create the list of all neighborhood ratings of an user. (very similar to the user occurrences list)
The list should list each rating as a card.
Each card should have a button to delete and edit a rating.
The list of ratings should be updated after an edit or a delete.
The screen should follow the prototype.

![Prototype profile](https://user-images.githubusercontent.com/29635581/97223704-e2b20d00-17ae-11eb-8f12-58a94046d760.png)
![Prototype rating list](https://user-images.githubusercontent.com/29635581/97223775-fe1d1800-17ae-11eb-94db-5ec768e80f9c.png)

## Tasks:
- [x] Create the button on the user profile.
- [x] Create the screen to list all user ratings.
- [x] Create the edit funcionality.
- [x] Create the delete funcionality.
