### ISSUE TITLE
Insert SP coordinates in frontend

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#62]
## Issue Description
Use the SP heat map generating functionality and monitore time spent to generate the full map.

Run coordinates crawler in secretary-service and save output directly in frontend, use this data to build heat map, in the same way DF is made.

Run the same functionality and report performance increase when doing this refactoring. If substantial try to generalize methods to use them both in DF and SP heat map.
 
## Additional context
For more information you can check issue [Get SP cities coordinates](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/issues/35).

## Tasks:
- [x] Monitore time before changes
- [x] Save coordinates in frontend and delete the request to get coordinates
- [x] Monitore time after changes 
- [x] Generalize code if needed

**Comment by lboaventura25** [comment]
The time before changes is estimate in 55 seconds.

**Comment by lboaventura25** [comment]
The time after changes is estimate in 25 seconds.

**Comment by lboaventura25** [comment]
@renan601, @silvasara, @rossicler, @herickport, @alvesitalo, @tsrrodrigues, @danieldagerom, @LuizPettengill and @brendavsantos, what do you think about that?

**Comment by silvasara** [comment]
@lboaventura25 let's keep json at the front then. It's still have a high time, but the improvement was quite significant
