### ISSUE TITLE
Create, view and delete favorite places of an user

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-front-end#65]
## Issue Description
Create e button on the user profile to see all his favorite places.
Create a list of favorite places set by the user, showing the name of the place.
Add a delete button to each card of the list.
Create a float '+' button on the right bottom corner of the list to add a new favorite place.
When adding a new favorite place, the user should select a position in a map and then write a name to the place selected, or the map should get the name of the selected position using the google maps api.

## Tasks:
- [x] Create the functionality to add a new favorite place.
- [x] Create list of favorite places.
- [x] Create delete button for each favorite place.

**Comment by herickport** [comment]
Can a user click on one of their favorite places and go to the place on the map?
