### ISSUE TITLE
Setup Sonarqube

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-front-end#69]
## Issue Description
Setup Sonarqube to make a code scan in the repository

## Tasks:
- [x] Search how to use Sonarqube
- [x] Setup Sonarqube scan
- [x] Update readme with all the instructions
