### ISSUE TITLE
Search screen

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-front-end#73]
## Issue Description
Implement a search screen where you can search by neighborhood and city.

While typing the name in the search field, suggestions of name should be displayed to the user.

When a search is made for the neighborhood, it should be taken to the screen that shows the assessment statistics for that neighborhood and through which it is also possible to register an assessment.
When searching for a city, it should be taken at the screen that shows the crime statistics for that city.

The requests for the backend that will bring the names of the cities and neighborhoods must be made when the application is started and the responses must be stored in storage of app.

## Tasks:
- [x] Store cities and neighborhoods names.
- [x] Implement the screen
- [x] Link the statistics city screen
- [x] Link the statistics neighborhood screen
