### ISSUE TITLE
Make some aspects clear to users

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-front-end#82]
## Issue Description
With the acceptance tests it was noticed the need for changes to make some aspects more clear to users:

## Tasks:
- [x] Standardize the language used in the application for Portuguese. (ex: in the user there are fields in English and Portuguese)
- [x] Start the DF map with a larger zoom
- [x] On the information card of the heat map, inform which period the data shown on the map is from, for this use the dates being passed as a filter in the request for the backend.
- [x] Improve question about the occurrence report in the register and edition of occurrence. Suggestion: "Você registrou boletim de ocorrência?" or "Foi registrado boletim de ocorrência?"
- [x] Improve question about the user be a victim or a witness  in the register and edition of occurrence. Suggestion: "Você foi a vítima da ocorrência?" or "Você foi vítima ou testemunha?"
- [x] Improve the text in the neighborhood assessment details to make it clear that it is optional. Suggestion: "Se desejar, forneça mais detalhes da sua avaliação." 
- The last three changes may require changes to the screen layout if the text size does not look good on the screen.
