### ISSUE TITLE
Map improvements

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-front-end#89]
## Issue Description
From the acceptance tests and conversations of the team we realized that some improvements in the maps need to be made.
Currently when the filter modal is opened the map is reloaded, this reloading is unnecessary and needs to be removed.
After registering an occurrence the ideal is that the application returns to the map where the user was when he registered, currently this is not happening.
Another improvement is when choosing a place to be a favorite, a "clean" map should be displayed to the user.

## How it will be validated
To validate the issue the following tests will be done:

- In the heat map, the reviewer will click on the filter button and when the modal opens the expected behavior, the map behind it will not be loaded.
- The reviewer will register an occurrence and when he finishes it is expected to see the same map he/she/they was on when the registration started.
- The reviewer will click on the favorite location button and it is expected that a map with no markings and no colors will appear for him/her

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Do not load the map when the filter modal is opened
- [x] Return to the map that the user was on when registering the occurrence
- [x] Display a clean map for choosing favorites
