### ISSUE TITLE
Occurrence registration

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#9]
## Issue Description
Make a screen for occurrence registration with the [prototype](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/produto/prototype/) style. In case of suggestions for changes, inform the team that we will discuss this together.

Make sure to validate data and show user friendly messages in case of problems in any field. Follow the validations available in the [occurence crud issue](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/issues/2) and [topic 5 of architecture document](https://fga-eps-mds.github.io/2020.1-stay-safe-docs/projeto/arquitetura/). No need to collect "register_date_time", this field is in backend responsibility. 

When receiving a backend success code show user a modal saying "Your occurrence was successfully registered" and redirect him to the home page.

## Additional context
The defined functionality must communicate with the backend, the type of request to be made (post) can be found in the [occurrence view file](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/blob/develop/src/views/occurrence.py).

## Tasks:
- [x] Implement occurrence register screen
- [x] Make all necessary validations 
- [x] Receive success message and redirect user
