### ISSUE TITLE
Get the crimes of the last 12 months

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-front-end#90]
## Issue Description
To comply with what was agreed in the group, the crimes displayed to the user must be those of the last 12 months, so, in the request made for the backend, the final_month must be the current month, which must be obtained dynamically, and the initial_month must be the equivalent of one year before the current month.

## How it will be validated
To validate the issue the following tests will be done:

- The reviewer will look at the code how is the current month is being defined, is expected it is not being statically defined, as well as a month that will be the equivalent of a year ago.
- The reviewer will look at how the request to obtain the data for the heat map is being made, the expectation is that the request query has the current month as the final_month, and the month equivalent to a year ago as the initial_month.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Get the final_month as the current one dynamically
- [x] Get the initial_month from the final_month dynamically
- [x] Update the query made for the backend with the months mentioned
