### ISSUE TITLE
Improve dark mode and make it default

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#91]
## Issue Description
From the acceptance tests and conversations of the team we realized that some improvements in the maps need to be made.

Some elements of the application are impaired when using dark mode (like the search in the cities dropdown where the inserted text mix with the background color), switch the color used in this element to better fit the app, if you find any other critical points contact the team so that we increment the issue. 

Switch the default app theme to dark, we agreed in group with these decision because the dark theme provide better continuous use without any eye strain. 

The clear theme can be accessed through the settings (the same way it works already), if the user switches to the clear mode this information must be saved in the storage, so that when he closes and opens the application the clear theme is loaded by default (this logic is already implemented for dark-theme).

## How it will be validated
To validate the issue the following tests will be done:
* The reviewer will open the application with no saved cache and check if the dark theme is enabled.
* The reviewer will load search screen and check if the inconsistency of colors in the input is fixed.
* The reviewer will switch to the clear theme and check if it works correctly.
* The reviewer will close and open the app and check if the clear theme selected before is open by default.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Fix visual inconsistency on the search screen
- [x] Search the application for other possible color problems
- [x] Set dark-theme as default
- [x] Enable clear-theme to be loaded on storage when selected
