### ISSUE TITLE
Create floating button to group icons in the map 

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-front-end#92]
## Issue Description
From the acceptance tests and conversations of the team we realized that some improvements in the maps need to be made.

The different maps are the main features of our application, but some factors hinder their usability for new users. Among these factors we can mention the excess of icons that appear on the map and how the change from heat map to occurrence map is made.

To solve these problems the solution proposed and agreed in group was to create a new floating button to group icons, all elements currently floating on the map must be put inside this element.

This floating button must be represented with an icon with three vertical points. When opened the first option must be to switch from heat map to occurrence map and vice versa, the second option should be the filter button (specific for heat or occurrence maps like already works in the app) and the third option must be the information icon with the same content that already has.

One logic already working specific to heat map must be preserved, the logic is: When a user selects heat map open the filter component automatically so that he properly insert the crime type and state to generate heat map. The heat map is generated only with options selected in the filter component, while the occurrence map works with or without those options selected.

The issue to break maps in occurrence and heat can show more details: https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/83

## How it will be validated
To validate the issue the following tests will be done:
* The reviewer will open the created button and check the change between occurrence map and heat map.
* The reviewer will check the filter options in heat and occurrence map and verify if the current behavior hasn't changed.
* The reviewer will check the extra information option in heat and occurrence map and verify if the current behavior hasn't changed.
* The reviewer will check if the current behavior of filter option in heat map hasn't changed.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Create floating button to group icons
- [x] Insert working icons inside
- [x] Adapt map change logic and insert as a option inside floating button

## Additional context
Example:
![photo5035414375476865345](https://user-images.githubusercontent.com/26857903/100028151-a4673800-2dc4-11eb-9cf8-820c8c1b76fc.jpg)
