### ISSUE TITLE
Refactor search to remove neighborhood

### ISSUE THREAD

**Issue by rossicler** [fga-eps-mds/2020.1-stay-safe-front-end#93]
## Issue Description
The search screen is now searching for 3 different selects, one to the state, one to the city and the last one to the neighborhood. The search now should have only one select that it's gonna filter by the state. The default value of the select is no filter, so it should list all cities, then if the user wants, he can select a state to filter the list.
The list of cities should have a search input that with every change, the app will search by it's value.
When a user click on a city, the app should navigate to the city screen.

## How it will be validated
To validate the issue the following tests will be done:

- The reviewer will open the search screen and see a list of all cities of DF and SP.
- The reviewer will open the search screen and filter by the DF state, the list should be updated with only DF cities.
- The reviewer will open the search screen and type "Gama" on the search input, the list should show only the "Gama" item, then the reviewer should click on the item to navigate to the city screen.

If the tests are successful, the issue will be considered ready.

## Tasks:
- [x] Remove neighborhood filter.
- [x] Remove cities select and add to a list with a search input that updates on change.
- [x] Change, if necessary, the state select to act as a filter (it should only filter if a value is selected, if not, it should show all cities)
